# Generated by Django 5.2.11 on 2026-02-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagevehicule_id_alter_vehicule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionVehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Option')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Option véhicule',
                'verbose_name_plural': 'Options véhicule',
                'ordering': ['ordre'],
            },
        ),
    ]
