# Generated by Django 5.2.11 on 2026-02-18 10:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imagevehicule_image_url_and_optional_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('raison', models.CharField(choices=[('vendre', 'Vendre son véhicule'), ('interesse', 'Intéressé par un véhicule'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de rendez-vous',
                'verbose_name_plural': 'Demandes de rendez-vous',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RendezVousFichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=core.models.contact_upload_to)),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='core.rendezvous')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
