# Generated by Django 6.0.5 on 2026-05-31 17:52

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_imagevehicule_id_alter_optionvehicule_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('controle_technique', 'Contrôle technique'), ('rapport_entretien', "Rapport d'entretien"), ('carte_grise', 'Carte grise'), ('carte_grise_ancienne', 'Ancienne carte grise'), ('facture', 'Facture'), ('garantie', 'Garantie'), ('contrat', 'Contrat / cession'), ('expertise', "Rapport d'expertise"), ('autre', 'Autre')], max_length=40)),
                ('titre', models.CharField(blank=True, help_text='Libelle libre (ex. CT 2024, révision 15 000 km).', max_length=200)),
                ('fichier', models.FileField(upload_to=documents.models.document_upload_to)),
                ('date_document', models.DateField(blank=True, help_text='Date figurant sur le document (CT, facture, etc.).', null=True, verbose_name='Date du document')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicules',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
